repos:
  - repo: local
    hooks:
      - id: policy-sort
        name: Check policy action sort order
        entry: python hacking/check_policy_sort.py
        language: python
        additional_dependencies: [PyYAML]
        files: ^aws/policy/.*\.yaml$
        pass_filenames: false
