Version: '2012-10-17'
Statement:
  - Sid: AllowGlobalUnrestrictedResourceActionsWhichIncurNoFees
    Effect: Allow
    Action:
      ###
      # These cloudformation permissions simply enable use of the Cloud Control API.
      # The underlying resources the API is managing would still require their own permissions.
      - cloudformation:CancelResourceRequest
      - cloudformation:CreateResource
      - cloudformation:DeleteResource
      - cloudformation:Describe*
      - cloudformation:Get*
      - cloudformation:List*
      - cloudformation:UpdateResource
      ###
      - cloudwatch:Describe*
      - codebuild:BatchGetProjects
      - codebuild:CreateProject
      - codebuild:DeleteProject
      - codebuild:List*
      - codebuild:UpdateProject
      - codecommit:CreateRepository
      - codecommit:DeleteRepository
      - codecommit:Get*
      - codecommit:List*
      - codecommit:UpdateRepositoryDescription
      - codepipeline:CreatePipeline
      - codepipeline:DeletePipeline
      - codepipeline:Get*
      - codepipeline:List*
      - codepipeline:UpdatePipeline
      - ec2messages:AcknowledgeMessage
      - ec2messages:DeleteMessage
      - ec2messages:FailMessage
      - ec2messages:Get*
      - ec2messages:SendReply
      - events:CreateRule
      - events:DeleteRule
      - events:Describe*
      - events:List*
      - events:PutRule
      - events:PutTargets
      - events:RemoveTargets
      - glue:Get*
      - kinesis:Describe*
      - kinesis:List*
      - mq:CreateBroker
      - mq:CreateTags
      - mq:DeleteBroker
      - mq:Describe*
      - mq:List*
      - ses:CreateReceiptRuleSet
      - ses:DeleteIdentity
      - ses:DeleteIdentityPolicy
      - ses:DeleteReceiptRuleSet
      - ses:Describe*
      - ses:Get*
      - ses:List*
      - ses:PutIdentityPolicy
      - ses:SetActiveReceiptRuleSet
      - ses:SetIdentityDkimEnabled
      - ses:SetIdentityFeedbackForwardingEnabled
      - ses:SetIdentityHeadersInNotificationsEnabled
      - ses:SetIdentityNotificationTopic
      - ses:VerifyDomainDkim
      - ses:VerifyDomainIdentity
      - ses:VerifyEmailIdentity
      - sqs:CreateQueue
      - sqs:DeleteQueue
      - sqs:Get*
      - sqs:List*
      - sqs:SetQueueAttributes
      - sqs:TagQueue
      - sqs:UntagQueue
      - SNS:CreateTopic
      - SNS:DeleteTopic
      - SNS:Get*
      - SNS:List*
      - SNS:Publish
      - SNS:TagResource
      - SNS:SetSubscriptionAttributes
      - SNS:SetTopicAttributes
      - SNS:Subscribe
      - SNS:Unsubscribe
      - SNS:UntagResource
      - ssmmessages:CreateControlChannel
      - ssmmessages:CreateDataChannel
      - ssmmessages:OpenControlChannel
      - ssmmessages:OpenDataChannel
      - ssm:AddTagsToResource
      - ssm:Describe*
      - ssm:Get*
      - ssm:List*
      - ssm:PutComplianceItems
      - ssm:PutConfigurePackageResult
      - ssm:PutInventory
      - ssm:RemoveTagsFromResource
      - ssm:StartSession
      - ssm:TerminateSession
      - ssm:UpdateAssociationStatus
      - ssm:UpdateInstanceAssociationStatus
      - ssm:UpdateInstanceInformation
      - states:CreateStateMachine
      - states:DeleteStateMachine
      - states:Describe*
      - states:List*
      - states:StartExecution
      - states:StopExecution
      - states:TagResource
      - states:UpdateStateMachine
      - states:UntagResource
    Resource: "*"

  - Sid: AllowGlobalResourceRestrictedActionsWhichIncurNoFees
    Effect: Allow
    Action:
      - ssm:CreateDocument
      - ssm:DeleteDocument
      - cloudformation:CreateChangeSet
      - cloudformation:CreateStack
      - cloudformation:DeleteChangeSet
      - cloudformation:DeleteStack
      - cloudformation:SetStackPolicy
      - cloudformation:UpdateStack
      - cloudformation:UpdateTerminationProtection
      - cloudwatch:DeleteAlarms
      - cloudwatch:PutMetricAlarm
      - glue:DeleteCrawler
      - glue:DeleteJob
      - glue:TagResource
      - glue:UntagResource
      - glue:UpdateCrawler
      - glue:UpdateJob
      - kinesis:AddTagsToStream
      - kinesis:RemoveTagsFromStream
      - kinesis:StartStreamEncryption
      - kinesis:StopStreamEncryption
      - ssm:DeleteParameter
      - ssm:PutParameter
    Resource:
      - 'arn:aws:ssm:{{ aws_region }}:{{ aws_account_id }}:document/*'
      - 'arn:aws:cloudformation:{{ aws_region }}:{{ aws_account_id }}:stack/*'
      - 'arn:aws:cloudwatch:{{ aws_region }}:{{ aws_account_id }}:alarm:*'
      - 'arn:aws:glue:{{ aws_region }}:{{ aws_account_id }}:crawler/*'
      - 'arn:aws:glue:{{ aws_region }}:{{ aws_account_id }}:job/*'
      - 'arn:aws:kinesis:{{ aws_region }}:{{ aws_account_id }}:stream/*'
      - 'arn:aws:ssm:{{ aws_region }}:{{ aws_account_id }}:parameter/*'
      - 'arn:aws:ssm:{{ aws_region }}::parameter/aws/service/*'

  - Sid: AllowGlobalRestrictedResourceActionsWhichIncurFees
    Effect: Allow
    Action:
      - kinesis:CreateStream
      - kinesis:DecreaseStreamRetentionPeriod
      - kinesis:DeleteStream
      - kinesis:IncreaseStreamRetentionPeriod
      - kinesis:UpdateShardCount
      - glue:CreateCrawler
      - glue:CreateJob
    Resource:
      - 'arn:aws:kinesis:{{ aws_region }}:{{ aws_account_id }}:stream/*'
      - 'arn:aws:glue:{{ aws_region }}:{{ aws_account_id }}:crawler/*'
      - 'arn:aws:glue:{{ aws_region }}:{{ aws_account_id }}:job/*'

  # Used to test some of the cross-account features
  - Sid: PermitReadOnlyThirdParty
    Effect: Allow
    Action:
      - SNS:Subscribe
      - SNS:Unsubscribe
    Resource:
      # https://aws.amazon.com/blogs/aws/subscribe-to-aws-public-ip-address-changes-via-amazon-sns/
      - 'arn:aws:sns:us-east-1:806199016981:AmazonIpSpaceChanged'
