Version: '2012-10-17'
Statement:

  - Sid: AllowRegionalRestrictedResourceActionsWhichIncurFees
    Effect: Allow
    Action:
      - wafv2:List*
      - wafv2:AssociateWebACL
      - wafv2:DeleteRuleGroup
      - wafv2:CreateRuleGroup
      - wafv2:PutFirewallManagerRuleGroups
      - wafv2:Get*
      - wafv2:DeleteWebACL
      - wafv2:CreateWebACL
      - wafv2:CreateIPSet
      - wafv2:DeleteIPSet
      - wafv2:Describe*
      - wafv2:CheckCapacity
      - wafv2:DeleteLoggingConfiguration
      - wafv2:PutLoggingConfiguration
      - wafv2:DisassociateWebACL
      - wafv2:UpdateWebACL
      - wafv2:UpdateRuleGroup
      - wafv2:DeleteFirewallManagerRuleGroups
      - wafv2:DisassociateFirewallManager
      - wafv2:UpdateIPSet
    Resource:
      - 'arn:aws:wafv2:{{ aws_region }}:{{ aws_account_id }}:*'

  - Sid: AllowRegionalUnrestrictedResourceActionsWhichIncurNoFees
    Effect: Allow
    Action:
      - inspector:List*
      - inspector:CreateResourceGroup
      - inspector:CreateAssessmentTarget
      - inspector:Describe*
      - inspector:UpdateAssessmentTarget
      - inspector:DeleteAssessmentTarget
      - inspector:CreateAssessmentTemplate
      - inspector:DeleteAssessmentTemplate
      - inspector:SetTagsForResource
      - waf:CreateByteMatchSet
      - waf:CreateGeoMatchSet
      - waf:CreateIPSet
      - waf:CreateRateBasedRule
      - waf:CreateRegexMatchSet
      - waf:CreateRegexPatternSet
      - waf:CreateRule
      - waf:CreateRuleGroup
      - waf:CreateSizeConstraintSet
      - waf:CreateSqlInjectionMatchSet
      - waf:CreateWebACL
      - waf:CreateXssMatchSet
      - waf:DeleteByteMatchSet
      - waf:DeleteGeoMatchSet
      - waf:DeleteIPSet
      - waf:DeleteRateBasedRule
      - waf:DeleteRegexMatchSet
      - waf:DeleteRegexPatternSet
      - waf:DeleteRule
      - waf:DeleteRuleGroup
      - waf:DeleteSizeConstraintSet
      - waf:DeleteSqlInjectionMatchSet
      - waf:DeleteWebACL
      - waf:DeleteXssMatchSet
      - waf:Get*
      - waf:List*
      - waf:TagResource
      - waf:UntagResource
      - waf:UpdateByteMatchSet
      - waf:UpdateGeoMatchSet
      - waf:UpdateIPSet
      - waf:UpdateRateBasedRule
      - waf:UpdateRegexMatchSet
      - waf:UpdateRegexPatternSet
      - waf:UpdateRule
      - waf:UpdateSizeConstraintSet
      - waf:UpdateSqlInjectionMatchSet
      - waf:UpdateWebACL
      - waf:UpdateXssMatchSet
      - wafv2:List*
      - wafv2:TagResource
      - wafv2:UntagResource
    Resource: "*"
    Condition:
      StringEquals:
        aws:RequestedRegion:
          - '{{ aws_region }}'
